import React, { useState, useEffect } from "react";
import axios from "axios";
import { Link } from "react-router-dom";
import { ChevronRight } from "lucide-react";
import {
  Card,
  CardHeader,
  Input,
  Dialog,
  Typography,
  Button,
  CardBody,
  Chip,
  CardFooter,
  Avatar,
  IconButton,
  Tooltip,
  Select,
  Option,
} from "@material-tailwind/react";
import {
  PDFDownloadLink,
  Document,
  Page,
  Text,
  View,
  StyleSheet,
} from "@react-pdf/renderer";
import { useCompany } from "../contexts/CompanyContext";

import * as XLSX from "xlsx";

const LateReport = () => {
  const { companyName } = useCompany();
  const storedUser = localStorage.getItem('userName');

 const LoggedUser = storedUser.replace(/["\n]/g, '').trim();
  const [startDate, setStartDate] = useState("");
  const [endDate, setEndDate] = useState("");
  const [reportData, setReportData] = useState([]);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState("");
  const [searchTerm, setSearchTerm] = useState("");
  const [currentPage, setCurrentPage] = useState(1);
  const [itemsPerPage] = useState(12);

  const exportToExcel = () => {
    // Step 1: Convert data to worksheet
    const ws = XLSX.utils.json_to_sheet(
      filteredData.map((row) => ({
        "ID": row.employeeid ,
        "Name": row.employeename ,
        "Designation": row.designation ,
        "Department": row.department,
        "Date": row.punchindate,
         "Shift": row.shift || "-",
        "Shift InTime":   row.shiftintime || "-",
        "Punch Intime":   row.punchintime,
      
        "Late Hrs": formatTime(row.lateminutes),
      }))
    );

    // Step 4: Create a new workbook and append the worksheet
    const wb = XLSX.utils.book_new();
    XLSX.utils.book_append_sheet(wb, ws, "Late Report");

    // Step 5: Export the workbook as a file
    XLSX.writeFile(wb, "Late Report.xlsx");
  };

  const MyDocument = () => {
    const styles = StyleSheet.create({
      page: {
        padding: 20,
        fontFamily: "Helvetica",
        fontSize: 10,
      },
      section: {
        marginBottom: 20,
      },
      table: {
        display: "table",
        width: "100%",
        borderStyle: "solid",
        borderColor: "#000",
        borderWidth: 1,
        marginTop: 10,
      },
      tableRow: {
        flexDirection: "row",
        backgroundColor: "#f0f0f0",
        borderBottom: "1px solid #ddd",
      },
      tableHeaderRow: {
        flexDirection: "row",
        backgroundColor: "#e0e0e0", // Slightly different color for header
      },
      tableCell: {
        padding: 5,
        borderRight: "1px solid #ddd",
        textAlign: "center",
      },
      tableHeaderCell: {
        fontWeight: "bold",
        padding: 5,
        textAlign: "center",
        borderRight: "1px solid #ddd",
      },
      columnID: {
        width: 50,
      },
      columnFlex: {
        flex: 1,
      },
      columnLateHrs: {
        width: 50,
      },
      title: {
        fontSize: 11,
        fontWeight: "bold",
        textAlign: "left", // Center title
      },
      headerRow: {
        flexDirection: "row", // Create a horizontal layout for Generated By and Company Name
        justifyContent: "space-between", // Space out the two elements
        marginBottom: 10,
      },
      generatedByText: {
        fontSize: 11,
        fontWeight: "bold",
        textAlign: "left", // Left-aligned text
        flex: 1, // Allow this section to take available space
      },
      companyText: {
        fontSize: 11,
        fontWeight: "bold",
        textAlign: "right", // Right-aligned text
        flex: 1, // Allow this section to take available space
      },
      dateText: {
        fontSize: 11,
        textAlign: "right", // Center Date Range
        marginVertical: 5,
      },
    });

    return (
      <Document>
        <Page style={styles.page}>
          <View style={styles.section}>
          <View style={styles.headerRow}>
          <Text style={styles.title}>Report Type :Late Report </Text>
<Text style={styles.dateText}>Generated from: {startDate} to  {endDate}</Text>
</View>
<View style={styles.headerRow}>
  <Text style={styles.generatedByText}>Generated by: {LoggedUser}</Text>
  <Text style={styles.companyText}>Company Name: {companyName}</Text>
</View>


            {/* Table */}
            <View style={styles.table}>
              {/* Table Header */}
              <View style={styles.tableHeaderRow}>
                <Text style={[styles.tableHeaderCell, styles.columnID]}>
                  ID
                </Text>
                <Text style={[styles.tableHeaderCell, styles.columnFlex]}>
                  Name
                </Text>
                <Text style={[styles.tableHeaderCell, styles.columnFlex]}>
                  Designation
                </Text>
                <Text style={[styles.tableHeaderCell, styles.columnFlex]}>
                  Department
                </Text>
                <Text style={[styles.tableHeaderCell, styles.columnFlex]}>
                  Date
                </Text>
                <Text style={[styles.tableHeaderCell, styles.columnFlex]}>
                  Shift In Time
                </Text>
                <Text style={[styles.tableHeaderCell, styles.columnFlex]}>
                  In Time
                </Text>
                <Text style={[styles.tableHeaderCell, styles.columnLateHrs]}>
                  Late Hrs
                </Text>
              </View>

              {/* Table data */}
              {filteredData.map((row, index) => (
                <View key={index} style={styles.tableRow}>
                  <Text style={[styles.tableCell, styles.columnID]}>
                    {row.employeeid}
                  </Text>
                  <Text style={[styles.tableCell, styles.columnFlex]}>
                    {row.employeename}
                  </Text>
                  <Text style={[styles.tableCell, styles.columnFlex]}>
                    {row.designation}
                  </Text>
                  <Text style={[styles.tableCell, styles.columnFlex]}>
                    {row.department}
                  </Text>
                  <Text style={[styles.tableCell, styles.columnFlex]}>
                   {row.punchindate}
                  </Text>
                  <Text style={[styles.tableCell, styles.columnFlex]}>
                    {row.shiftintime || "-"}
                  </Text>
                  <Text style={[styles.tableCell, styles.columnFlex]}>
                    {row.punchintime
                      }
                  </Text>
                  <Text style={[styles.tableCell, styles.columnLateHrs]}>
                    {formatTime(row.lateminutes)}
                  </Text>
                </View>
              ))}
            </View>
          </View>
        </Page>
      </Document>
    );
  };

  useEffect(() => {
    const today = new Date();
    const sevenDaysAgo = new Date(today);
    sevenDaysAgo.setDate(today.getDate() - 2);

    const startDateString = sevenDaysAgo.toISOString().split("T")[0]; // Format as YYYY-MM-DD
    const endDateString = today.toISOString().split("T")[0]; // Format as YYYY-MM-DD

    setStartDate(startDateString);
    setEndDate(endDateString);
  }, []);

  useEffect(() => {
    if (startDate && endDate) {
      fetchReport();
    }
  }, [startDate, endDate]); // This effect runs when startDate or endDate changes

  const fetchReport = async () => {
    setLoading(true);
    setError("");

    try {
      const response = await axios.get(
        `${import.meta.env.VITE_API_URL}/api/Reports/Late-report`,
        {
          params: { startDate, endDate },
        }
      );
      setReportData(response.data.data);
      console.log(response.data.data);
    } catch (error) {
      console.error("Error fetching report:", error);
      setError("Failed to fetch the report. Please try again.");
    } finally {
      setLoading(false);
    }
  };

  // Filter report data based on search term
  const filteredData = reportData.filter((row) =>
    row.employeename.toLowerCase().includes(searchTerm.toLowerCase())
  );

  function formatTime(minutes) {
    if (!minutes || minutes === "-") return "-"; // If no value is provided, return '-'

    // Convert minutes to total seconds and round to the nearest whole second
    const totalSeconds = Math.round(minutes * 60);

    // Calculate hours, minutes, and seconds
    const hours = Math.floor(totalSeconds / 3600);
    const mins = Math.floor((totalSeconds % 3600) / 60);
    const secs = totalSeconds % 60;

    // Return formatted time as HH:MM:SS
    return `${String(hours).padStart(2, "0")}:${String(mins).padStart(
      2,
      "0"
    )}:${String(secs).padStart(2, "0")}`;
  }

  // Paginate the filtered data
  const indexOfLastItem = currentPage * itemsPerPage;
  const indexOfFirstItem = indexOfLastItem - itemsPerPage;
  const currentItems = filteredData.slice(indexOfFirstItem, indexOfLastItem);

  const totalPages = Math.ceil(filteredData.length / itemsPerPage);

  const handleNextPage = () => {
    if (currentPage < totalPages) {
      setCurrentPage((prevPage) => prevPage + 1);
    }
  };

  const handlePrevPage = () => {
    if (currentPage > 1) {
      setCurrentPage((prevPage) => prevPage - 1);
    }
  };

  return (
    <div className="max-w-7xl mx-auto">
      {/* Form Section */}
      <div className="mb-2">
        <nav className="flex" aria-label="Breadcrumb">
          <ol className="inline-flex items-center space-x-1 md:space-x-3">
            <li className="inline-flex items-center">
              <Link
                to="/reports"
                className="inline-flex items-center text-gray-700 hover:text-blue-600"
              >
                Reports
              </Link>
            </li>
            <li>
              <div className="flex items-center">
                <ChevronRight className="w-4 h-4 text-gray-400" />
                <span className="ml-1 text-gray-500 md:ml-2">Late Report</span>
              </div>
            </li>
          </ol>
        </nav>
      </div>
      <div className="bg-white rounded-lg shadow-md p-3 mb-3">
        <div className="flex space-x-6">
          <input
            type="text"
            placeholder="Search by Employee Name"
            value={searchTerm}
            onChange={(e) => setSearchTerm(e.target.value)}
            className="w-60 h-15 mt-7 p-3 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-indigo-500 text-sm"
          />

          <div className="w-[220px]">
            <label
              htmlFor="startDate"
              className="block text-sm font-medium text-gray-700"
            >
              Start Date
            </label>
            <input
              type="date"
              id="startDate"
              value={startDate}
              onChange={(e) => setStartDate(e.target.value)}
              className="mt-2 p-3 w-full border cursor-pointer border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-indigo-500 text-sm"
            />
          </div>

          <div className="w-[220px]">
            <label
              htmlFor="endDate"
              className="block text-sm font-medium text-gray-700"
            >
              End Date
            </label>
            <input
              type="date"
              id="endDate"
              value={endDate}
              onChange={(e) => setEndDate(e.target.value)}
              className="mt-2 p-3 w-full border cursor-pointer border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-indigo-500 text-sm"
            />
          </div>

          <button
            onClick={fetchReport}
            disabled={!startDate || !endDate || loading}
            className="w-30 h-15 px-3 mt-7 bg-blue-600 text-white rounded-md hover:bg-blue-700 disabled:bg-gray-400 text-sm transition duration-300"
          >
            {loading ? "Loading..." : "Get Report"}
          </button>

          <PDFDownloadLink document={<MyDocument />} fileName="LateReport.pdf">
            {({ loading }) =>
              loading ? (
                <Button className="bg-blue-600 w-30 h-10 mt-7 text-white hover:bg-blue-700 rounded-lg">
                  Generating PDF...
                </Button>
              ) : (
                <Button className="bg-red-400 w-30  mt-7 h-10 text-white hover:bg-red-700 rounded-lg">
                  PDF
                </Button>
              )
            }
          </PDFDownloadLink>
          <button
            onClick={exportToExcel}
            className=" bg-green-500 w-[60px] h-10 mt-7 text-white rounded-md hover:bg-green-600"
          >
            Excel
          </button>
        </div>
      </div>

      {/* Error Message */}
      {error && (
        <p className="text-red-500 text-center mb-4 text-sm">{error}</p>
      )}

      {/* Report Table */}
      {currentItems.length > 0 ? (
  <div className="overflow-x-auto bg-white shadow-md rounded-lg">
    <table className="min-w-full bg-white border-collapse table-auto text-sm cursor-pointer">
      <thead className="bg-gray-100">
        <tr>
          <th className="px-5 py-2 text-nowrap text-center font-medium text-gray-700">
            ID
          </th>
          <th className="px-8 py-2 text-nowrap text-left font-medium text-gray-700">
            Name
          </th>
          <th className="px-8 py-2 text-nowrap text-left font-medium text-gray-700">
            Designation
          </th>
          <th className="px-8 py-2 text-nowrap text-left font-medium text-gray-700">
            Department
          </th>
          <th className="px-8 text-nowrap text-left font-medium text-gray-700">
            Date
          </th>
          <th className="px-3 text-nowrap text-left font-medium text-gray-700">
            Shift In Time
          </th>
          <th className="px-3 text-nowrap text-left font-medium text-gray-700">
            In Time
          </th>
          <th className="px-3 text-nowrap text-left font-medium text-gray-700">
            Late Hrs
          </th>
        </tr>
      </thead>
      <tbody>
        {currentItems.length > 0 ? (
          currentItems.map((row, index) => (
            <tr
              key={index}
              className="border-b hover:bg-gray-50 transition duration-200 cursor-pointer"
            >
              <td className="px-5 py-2 text-nowrap text-left">
                {row.employeeid || "-"}
              </td>
              <td className="px-5 py-2 text-nowrap text-left">
                {row.employeename || "-"}
              </td>
              <td className="px-4 py-2 text-nowrap text-left">
                {row.designation || "-"}
              </td>
              <td className="px-4 py-2 text-nowrap text-left">
                {row.department || "-"}
              </td>
              <td className="px-4 text-nowrap text-left">
                {row.punchindate || "-"}
              </td>
              <td className="px-4 text-nowrap text-left">
                {row.shiftintime || "-"}
              </td>
              <td className="px-4 text-nowrap text-left">
                {row.punchintime || "-"}
              </td>
              <td className="px-4 text-nowrap text-left">
                {formatTime(row.lateminutes) || "-"}
              </td>
            </tr>
          ))
        ) : (
          <tr>
            <td className="text-center text-gray-500 py-4" colSpan="8">
              No matching records found.
            </td>
          </tr>
        )}
      </tbody>
    </table>
  </div>
) : (
  <div className="text-center text-gray-500 py-4">
    <p>No records available for Selected Dates</p>
  </div>
)}

      {/* Pagination Controls */}
      {filteredData.length > itemsPerPage && (
        <div className="flex justify-around items-center mt-4">
          <button
            onClick={handlePrevPage}
            disabled={currentPage === 1}
            className="px-4 py-2 bg-blue-300 text-sm rounded-md disabled:bg-gray-200"
          >
            Previous
          </button>
          <span className="text-sm">
            Page {currentPage} of {totalPages}
          </span>
          <button
            onClick={handleNextPage}
            disabled={currentPage === totalPages}
            className="px-4 py-2 bg-blue-300 text-sm rounded-md disabled:bg-gray-200"
          >
            Next
          </button>
        </div>
      )}
    </div>
  );
};

export default LateReport;
