const PDFDocument = require('pdfkit');
const convertMinutesToHHMM = require('../utils/convertminutestohhmm');

const generatePDF = (res, data, companyName, startDate, endDate, loggedUser) => {
  const doc = new PDFDocument({ size: 'A4', layout: '', margin: 20 });
  const dateTime = new Date().toLocaleString();

  res.setHeader('Content-Type', 'application/pdf');
  res.setHeader('Content-Disposition', 'attachment; filename=AttendanceReport.pdf');

  // Error handling
  doc.on('error', (err) => {
    console.error('PDF Error:', err);
    res.status(500).end();
  });

  res.on('error', (err) => {
    console.error('Response Error:', err);
  });

  const styles = {
    headerColor: '#2c3e50',
    accentColor: '#3498db',
    rowEvenColor: '#f8f9fa',
    rowOddColor: '#ffffff',
    footerColor: '#95a5a6',
    headerFontSize: 18,
    subHeaderFontSize: 10,
    tableHeaderFontSize: 10,
    bodyFontSize: 9,
  };

  const columns = [
    { header: 'ID', width: 40 },
    { header: 'C.Id', width: 50 },
    { header: 'Name', width: 80 },
    { header: 'Dept', width: 70 },
    { header: 'Device', width: 60 },
    { header: 'Date', width: 70 },
    { header: 'In', width: 50 },
    { header: 'Out', width: 50 },
    // { header: 'Late Hrs', width: 60, align: 'right' },
    // { header: 'OT Hrs', width: 60, align: 'right' },
    // { header: 'Early Hrs', width: 70, align: 'right' },
    { header: 'Total Hrs', width: 70, },
  ];

  let isEvenRow = false;
  let pageNumber = 1;

  const formatDate = (dateValue) => {
    if (!dateValue) return '--';
    const date = new Date(dateValue);
    return date.toLocaleDateString('en-CA'); // Local date in YYYY-MM-DD
  };

  const formatTime = (timeValue) => {
    if (!timeValue) return '--';
    const date = new Date(timeValue);
    return date.toLocaleTimeString('en-US', { // Local time in HH:MM
      hour: '2-digit',
      minute: '2-digit',
      hour12: false
    });
  };

  const addMainHeader = () => {
    doc.fillColor(styles.headerColor)
      .font('Helvetica-Bold')
      .fontSize(styles.headerFontSize)
      .text(`${companyName} Attendance Report`, { align: 'center' })
      .moveDown(0.3);

    doc.fontSize(styles.subHeaderFontSize)
      .text(`Generated by: ${loggedUser} | ${dateTime}`, { align: 'center' })
      .text(`Date Range: ${startDate} to ${endDate}`, { align: 'center' })
      .moveDown(1);

    doc.moveTo(40, doc.y).lineTo(doc.page.width - 40, doc.y).stroke();
  };

  const addFooter = () => {
    doc.save()
      .fontSize(styles.subHeaderFontSize)
      .fillColor(styles.footerColor)
      .text(`Page ${pageNumber}`, 40, doc.page.height - 40, { align: 'left' })
      .restore();
  };

  const createTableHeaders = () => {
    let y = doc.y + 5;
    doc.font('Helvetica-Bold').fontSize(styles.tableHeaderFontSize);
    let x = 40;

    columns.forEach((col) => {
      doc.fill(styles.headerColor)
        .rect(x, y, col.width, 20)
        .fillAndStroke(styles.headerColor, styles.headerColor);

      doc.fillColor('#ffffff')
        .text(col.header, x + 5, y + 5, {
          width: col.width - 10,
          align: col.align || 'left',
        });

      x += col.width;
    });

    doc.y = y + 20;
  };

  const createTableRow = (row) => {
    const rowColor = isEvenRow ? styles.rowEvenColor : styles.rowOddColor;
    isEvenRow = !isEvenRow;
    let x = 20;
    let y = doc.y;

    columns.forEach((col) => {
      doc.rect(x, y, col.width, 20)
        .fill(rowColor)
        .stroke('#e0e0e0');
      x += col.width;
    });

    x = 40;
    const rowData = [
      row.employee_id,
      row.companyid,
      row.employee_name,
      row.department_name,
      row.device_name,
      formatDate(row.work_date),
      (row.actual_in_time),
      (row.actual_out_time),
      // convertMinutesToHHMM(row.late_minutes || 0),
      // convertMinutesToHHMM(row.overtime_minutes || 0),
      // convertMinutesToHHMM(row.early_leave_minutes || 0),
      convertMinutesToHHMM(row.total_minutes || 0),
    ];

    rowData.forEach((cell, index) => {
      doc.fillColor('#000000')
        .font('Helvetica')
        .fontSize(styles.bodyFontSize)
        .text(cell, x + 5, y + 5, {
          width: columns[index].width - 5,
          align: columns[index].align || 'left',
        });
      x += columns[index].width;
    });

    doc.y += 20;
  };

  const createNewPage = () => {
    doc.addPage();
    pageNumber++;
    createTableHeaders();
    doc.y += 1;
  };

  doc.pipe(res);

  addMainHeader();
  createTableHeaders();

  data.forEach((row) => {
    if (doc.y + 25 > doc.page.height - 60) {
      addFooter();
      createNewPage();
    }
    createTableRow(row);
  });

  addFooter();

  doc.end();
};

module.exports = generatePDF;